/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.Menu;

import java.awt.Color;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class Ingresar_Datos extends javax.swing.JFrame implements Datos{

    int xMause,yMause;
    private  Color color,color1;
    public Ingresar_Datos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BG = new javax.swing.JPanel();
        Font = new javax.swing.JLabel();
        Letrero = new javax.swing.JPanel();
        TxLetrero = new javax.swing.JLabel();
        Pregunta = new javax.swing.JPanel();
        TPregunta = new javax.swing.JLabel();
        TxColor = new javax.swing.JLabel();
        p1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        ModosJuego = new javax.swing.JComboBox<>();
        Bjugar = new javax.swing.JPanel();
        Jugar = new javax.swing.JLabel();
        ColorS = new javax.swing.JPanel();
        ColorS1 = new javax.swing.JPanel();
        p2 = new javax.swing.JLabel();
        TxColor1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        Scroll = new javax.swing.JPanel();
        BSalida = new javax.swing.JPanel();
        Tsalida = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        BG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Font.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Img/fondo-del-código-binario-18787760.jpg"))); // NOI18N
        BG.add(Font, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 450));

        Letrero.setBackground(new java.awt.Color(102, 102, 102));
        Letrero.setToolTipText("");

        TxLetrero.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        TxLetrero.setForeground(new java.awt.Color(255, 255, 255));
        TxLetrero.setText("INGRESE DATOS DE LOS JUGADORES");

        Pregunta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Pregunta.setOpaque(false);

        TPregunta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TPregunta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Img/pregunta (1).png"))); // NOI18N
        TPregunta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TPreguntaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PreguntaLayout = new javax.swing.GroupLayout(Pregunta);
        Pregunta.setLayout(PreguntaLayout);
        PreguntaLayout.setHorizontalGroup(
            PreguntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TPregunta, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
        );
        PreguntaLayout.setVerticalGroup(
            PreguntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TPregunta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout LetreroLayout = new javax.swing.GroupLayout(Letrero);
        Letrero.setLayout(LetreroLayout);
        LetreroLayout.setHorizontalGroup(
            LetreroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LetreroLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(TxLetrero)
                .addGap(18, 18, 18)
                .addComponent(Pregunta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        LetreroLayout.setVerticalGroup(
            LetreroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LetreroLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(TxLetrero)
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LetreroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Pregunta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        BG.add(Letrero, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 570, 60));

        TxColor.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        TxColor.setText("INGRESE COLOR :");
        BG.add(TxColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, 160, 20));

        p1.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        p1.setText("INGRESE P1 :");
        BG.add(p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 110, 20));

        jTextField1.setBorder(null);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        BG.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 240, 30));

        jTextField2.setBorder(null);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        BG.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 240, 30));

        ModosJuego.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        ModosJuego.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Normal", "Rapido"}));
        ModosJuego.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ModosJuego.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BG.add(ModosJuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 340, 160, 30));

        Bjugar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        Jugar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Img/espiar (1).png"))); // NOI18N

        javax.swing.GroupLayout BjugarLayout = new javax.swing.GroupLayout(Bjugar);
        Bjugar.setLayout(BjugarLayout);
        BjugarLayout.setHorizontalGroup(
            BjugarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BjugarLayout.createSequentialGroup()
                .addComponent(Jugar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );
        BjugarLayout.setVerticalGroup(
            BjugarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Jugar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        BG.add(Bjugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 380, 40, 40));

        ColorS.setBackground(new java.awt.Color(255, 255, 255));
        ColorS.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ColorS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ColorS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ColorSMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ColorSLayout = new javax.swing.GroupLayout(ColorS);
        ColorS.setLayout(ColorSLayout);
        ColorSLayout.setHorizontalGroup(
            ColorSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 198, Short.MAX_VALUE)
        );
        ColorSLayout.setVerticalGroup(
            ColorSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );

        BG.add(ColorS, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, 200, 30));

        ColorS1.setBackground(new java.awt.Color(255, 255, 255));
        ColorS1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ColorS1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ColorS1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ColorS1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ColorS1Layout = new javax.swing.GroupLayout(ColorS1);
        ColorS1.setLayout(ColorS1Layout);
        ColorS1Layout.setHorizontalGroup(
            ColorS1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        ColorS1Layout.setVerticalGroup(
            ColorS1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        BG.add(ColorS1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 270, -1, -1));

        p2.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        p2.setText("INGRESE P2:");
        BG.add(p2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 140, 20));

        TxColor1.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        TxColor1.setText("INGRESE COLOR :");
        BG.add(TxColor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 240, 160, 20));
        BG.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 240, 10));
        BG.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 240, 10));

        Scroll.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                ScrollMouseDragged(evt);
            }
        });
        Scroll.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ScrollMousePressed(evt);
            }
        });

        BSalida.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        Tsalida.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        Tsalida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Tsalida.setText("X");
        Tsalida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TsalidaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TsalidaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TsalidaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout BSalidaLayout = new javax.swing.GroupLayout(BSalida);
        BSalida.setLayout(BSalidaLayout);
        BSalidaLayout.setHorizontalGroup(
            BSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Tsalida, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
        );
        BSalidaLayout.setVerticalGroup(
            BSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Tsalida, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout ScrollLayout = new javax.swing.GroupLayout(Scroll);
        Scroll.setLayout(ScrollLayout);
        ScrollLayout.setHorizontalGroup(
            ScrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ScrollLayout.createSequentialGroup()
                .addContainerGap(687, Short.MAX_VALUE)
                .addComponent(BSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        ScrollLayout.setVerticalGroup(
            ScrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ScrollLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        BG.add(Scroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void ScrollMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ScrollMousePressed
          xMause=evt.getX();
          yMause=evt.getY();
    }//GEN-LAST:event_ScrollMousePressed

    private void ScrollMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ScrollMouseDragged
        int x =evt.getXOnScreen();
        int y=evt.getYOnScreen();
        this.setLocation(x-xMause, y-yMause);
    }//GEN-LAST:event_ScrollMouseDragged

    private void TsalidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TsalidaMouseClicked
        System.exit(0);
    }//GEN-LAST:event_TsalidaMouseClicked

    private void TsalidaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TsalidaMouseEntered
         Tsalida.setForeground(Color.red);
    }//GEN-LAST:event_TsalidaMouseEntered

    private void TsalidaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TsalidaMouseExited
        Tsalida.setForeground(Color.black);
    }//GEN-LAST:event_TsalidaMouseExited

    private void ColorS1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ColorS1MouseClicked
        color= color.BLACK;
        color = JColorChooser.showDialog(this,"SELECCIONA COLOR", color);
        
        if(null==color){
            color =color.WHITE;
          ColorS1.setBackground(color);
        }
        ColorS1.setBackground(color);
        
    }//GEN-LAST:event_ColorS1MouseClicked

    private void ColorSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ColorSMouseClicked
        color1= color1.BLACK;
        color1 = JColorChooser.showDialog(this,"SELECCIONA COLOR", color1);
        
        if(null==color1){
            color1 =color1.WHITE;
          ColorS.setBackground(color1);
        }
        ColorS.setBackground(color1);
    }//GEN-LAST:event_ColorSMouseClicked

    private void TPreguntaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TPreguntaMouseClicked
         JOptionPane.showMessageDialog(null, ayudas);  
    }//GEN-LAST:event_TPreguntaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ingresar_Datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ingresar_Datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ingresar_Datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ingresar_Datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ingresar_Datos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BG;
    private javax.swing.JPanel BSalida;
    private javax.swing.JPanel Bjugar;
    private javax.swing.JPanel ColorS;
    private javax.swing.JPanel ColorS1;
    private javax.swing.JLabel Font;
    private javax.swing.JLabel Jugar;
    private javax.swing.JPanel Letrero;
    private javax.swing.JComboBox<String> ModosJuego;
    private javax.swing.JPanel Pregunta;
    private javax.swing.JPanel Scroll;
    private javax.swing.JLabel TPregunta;
    private javax.swing.JLabel Tsalida;
    private javax.swing.JLabel TxColor;
    private javax.swing.JLabel TxColor1;
    private javax.swing.JLabel TxLetrero;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel p1;
    private javax.swing.JLabel p2;
    // End of variables declaration//GEN-END:variables
}
